# Generated by Django 3.2.4 on 2021-06-06 01:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
