# Generated by Django 3.2.4 on 2021-06-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_creator', '0013_alter_game_game_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MyTournament_L0J2Q2I8G', max_length=36)),
                ('description', models.CharField(max_length=330, null=True)),
                ('startTime', models.TimeField(null=True)),
                ('endTime', models.TimeField(null=True)),
                ('phase', models.CharField(default='Registration', max_length=20)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_creator.game')),
            ],
        ),
    ]
