# Generated by Django 3.2.3 on 2021-07-15 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('submission', '0002_workspacetestsubmissionentry_tag'),
        ('match', '0008_merge_20210703_2159'),
        ('game_creator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentInfo',
            new_name='Tournament',
        ),
        migrations.RenameModel(
            old_name='TournamentParticipantWorkspaceACL',
            new_name='TournamentCreatorACL',
        ),
        migrations.RenameModel(
            old_name='TournamentCreatorWorkspaceACL',
            new_name='TournamentRegistration',
        ),
    ]
