# Generated by Django 3.2.3 on 2021-07-16 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20210715_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
