# Generated by Django 3.2.4 on 2021-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournamentinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinfo',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tournamentinfo',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
