# Generated by Django 3.2.4 on 2021-06-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20210629_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentinfo',
            old_name='game_id',
            new_name='game',
        ),
    ]
