# Generated by Django 3.2.3 on 2021-07-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_tournament_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_uuid',
        ),
    ]
