# Generated by Django 3.2.4 on 2021-06-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_rename_game_id_tournamentinfo_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentinfo',
            old_name='game',
            new_name='game_id',
        ),
    ]
