# Generated by Django 3.2.3 on 2021-07-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_tournament_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
