# Generated by Django 3.2.3 on 2021-07-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20210716_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='game_id',
            new_name='game',
        ),
    ]
