# Generated by Django 3.2.3 on 2021-07-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_rename_game_id_tournament_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='game',
            new_name='game_id',
        ),
    ]
