# Generated by Django 3.2.5 on 2021-07-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournamentparticipantworkspaceacl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentcreatorworkspaceacl',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipantworkspaceacl',
            unique_together=set(),
        ),
    ]
