# Generated by Django 3.2.3 on 2021-07-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_rename_game_tournament_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='game_id',
            new_name='game',
        ),
    ]
