# Generated by Django 3.2.5 on 2021-07-02 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0008_auto_20210702_1125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentcreatorworkspaceacl',
            unique_together={('user', 'tournament')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipantworkspaceacl',
            unique_together={('user', 'tournament')},
        ),
    ]
