# Generated by Django 3.2.3 on 2021-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_rename_game_id_tournament_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_match_generation_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(default='roundrobin', max_length=15),
        ),
    ]
