# Generated by Django 3.2.3 on 2021-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20210719_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='phase',
            field=models.CharField(choices=[('reg', 'Open For Registration'), ('sub', 'Open For Submission'), ('exec', 'Match Execution'), ('end', 'Tournament Ended')], default='reg', max_length=5),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('rr', 'Round Robin')], default='rr', max_length=6),
        ),
    ]
