# Generated by Django 3.2.3 on 2021-07-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_workspacetestsubmissionentry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsubmissionentry',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.submission'),
        ),
    ]
