# Generated by Django 3.2.3 on 2021-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20210719_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacetestsubmissionentry',
            name='is_test_choice',
            field=models.BooleanField(default=False),
        ),
    ]
