# Generated by Django 3.2.3 on 2021-07-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_workspacetestsubmissionentry_is_test_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacetestsubmissionentry',
            old_name='is_test_choice',
            new_name='is_test',
        ),
    ]
