# Generated by Django 3.2.3 on 2021-07-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranklist',
            name='user',
        ),
    ]
