# Generated by Django 3.2.3 on 2021-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210603_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
