# Generated by Django 3.2.3 on 2021-07-02 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('game_judge_code_language', models.CharField(default='', max_length=10)),
                ('game_visualization_code_language', models.CharField(default='', max_length=10)),
                ('game_title', models.CharField(default='Untitled', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GameCreatorWorkspaceACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_creator.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
