# Generated by Django 3.2.3 on 2021-06-04 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_uid', models.UUIDField(default=uuid.uuid4)),
                ('judge_code', models.FileField(upload_to='game/judge_code')),
                ('description_code', models.FileField(upload_to='game/description')),
            ],
        ),
    ]
