# Generated by Django 3.2.3 on 2021-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_creator', '0002_auto_20210604_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='judge_code',
            field=models.FileField(default=1234, upload_to='<django.db.models.fields.UUIDField>/judge_code'),
            preserve_default=False,
        ),
    ]
