# Generated by Django 3.2.3 on 2021-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_creator', '0003_game_judge_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_uid',
            field=models.CharField(default='39e9ae60f9414fb396212145741bf944', max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='judge_code',
            field=models.FileField(upload_to='<django.db.models.fields.CharField>/judge_code'),
        ),
    ]
