# Generated by Django 3.2.3 on 2021-06-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_creator', '0004_auto_20210604_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_uid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='judge_code',
            field=models.FileField(upload_to=''),
        ),
    ]
