# Generated by Django 3.2.3 on 2021-06-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_creator', '0005_auto_20210604_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description_code',
            field=models.FileField(default=1234, upload_to='c04c5bd7000b41749b2aea5164f24951/description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_uid',
            field=models.UUIDField(default='46ea7c9601c2485e86d14605d61c5621', unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='judge_code',
            field=models.FileField(upload_to='5ae68f0cdd024b63b35733075ace73e2/description'),
        ),
    ]
