# Generated by Django 3.2.3 on 2021-06-04 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_creator', '0006_auto_20210604_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description_code',
        ),
        migrations.RemoveField(
            model_name='game',
            name='judge_code',
        ),
        migrations.AddField(
            model_name='game',
            name='game_judge_code_language',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='game_title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
