# Generated by Django 3.2.3 on 2021-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_creator', '0008_rename_game_uid_game_game_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_visualization_code_language',
            field=models.CharField(default='', max_length=10),
        ),
    ]
