# Generated by Django 3.2.4 on 2021-06-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_creator', '0012_alter_gamecreatorworkspaceacl_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.CharField(default='Untitled', max_length=256),
        ),
    ]
