# Generated by Django 3.2.3 on 2021-07-02 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0001_initial'),
        ('tournament', '0001_initial'),
        ('game_creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('match_phase', models.CharField(default='waiting', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_creator.game')),
                ('submission0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player0_submission', to='submission.submission')),
                ('submission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_submission', to='submission.submission')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMatchTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_creator.game')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatchTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentinfo')),
            ],
        ),
    ]
