# Generated by Django 3.2.3 on 2021-07-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_phase',
        ),
        migrations.AddField(
            model_name='match',
            name='match_results',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
