# Generated by Django 3.2.3 on 2021-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210703_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_visibility',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
