# Generated by Django 3.2.3 on 2021-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_match_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_visibility',
            field=models.CharField(default='private', max_length=10),
        ),
    ]
