# Generated by Django 3.2.4 on 2021-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_match_match_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_results',
            field=models.CharField(default='Not Decided', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
