# Generated by Django 3.2.4 on 2021-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20210703_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='history_filepath',
            field=models.FilePathField(null=True, path='/media/anachor/windows/Users/User/Desktop/Code/Academic/L4T1/Software/OnlineAI/Onine_AI/media/matches/<django.db.models.fields.UUIDField>'),
        ),
    ]
