# Generated by Django 3.2.4 on 2021-07-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_alter_match_history_filepath'),
        ('match', '0007_auto_20210703_2009'),
    ]

    operations = [
    ]
