# Generated by Django 3.2.3 on 2021-07-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_merge_20210703_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (-1, 'Error'), (1, 'Running'), (2, 'Ended')], default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_visibility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Workspace Test Match')], default=1),
        ),
    ]
