# Generated by Django 3.2.5 on 2021-07-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='name',
            field=models.CharField(default='JobStatus', max_length=256, primary_key=True, serialize=False),
        ),
    ]
