# Generated by Django 3.2.5 on 2021-07-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210721_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus',
            name='need_to_reload',
        ),
    ]
