# Generated by Django 3.2.5 on 2021-07-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_jobstatus_need_to_reload'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='need_to_reload_jobs',
            field=models.BooleanField(default=True),
        ),
    ]
